"""create post table

Revision ID: 5d646af52241
Revises: 
Create Date: 2023-03-13 10:45:35.351156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app import db

# revision identifiers, used by Alembic.
revision = '5d646af52241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    db.Column('Id', db.Integer(), nullable=False),
                    db.Column('Title', db.String(length=200)),
                    db.Column('Content', db.Text()),
                    db.Column('Category', db.String(length=100)),
                    db.Column('Created_at', db.TIMESTAMP(),
                              server_default=db.func.current_timestamp()),
                    db.Column('Updated_at', db.TIMESTAMP(),
                              server_default=db.func.current_timestamp()),
                    db.Column('Status', db.String(length=100)),
                    db.PrimaryKeyConstraint('Id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('Id', mysql.INTEGER(display_width=11),
                              autoincrement=True, nullable=False),
                    sa.Column('Title', mysql.VARCHAR(
                        length=200), nullable=True),
                    sa.Column('Content', mysql.TEXT(), nullable=True),
                    sa.Column('Category', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('Created_date', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp()'), nullable=False),
                    sa.Column('Updated_date', mysql.TIMESTAMP(), server_default=sa.text(
                        'current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
                    sa.Column('Status', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.PrimaryKeyConstraint('Id'),
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
